version: '2'
services:
  postgresql:
    image: mdillon/postgis:9.4-alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=dbname
    ports:
      - 15432:5432

  test-functional:
    image: node:8
    depends_on:
      - postgresql
    links:
      - postgresql:postgresql.local
    build: .
    environment:
      - NODE_ENV=production
      - POSTGRESQL_HOST=postgresql.local
      - POSTGRESQL_PORT=5432
      - POSTGRESQL_USER=admin
      - POSTGRESQL_PASSWORD=12345
      - POSTGRESQL_NAME=dbname
    working_dir: /opt/app
    command: >
      /bin/sh -c "
        #set -e
        dockerize -wait tcp://$$POSTGRESQL_HOST:$$POSTGRESQL_PORT
        npm run --silent migrate:schema
        npm run --silent migrate:seeds
        npm run --silent migrate:testSeeds
        echo Starting application
        npm --silent start &
        sleep 5
        node -v
        npm run test:functional
        ps aux
      "

  run:
    depends_on:
      - postgresql
    build: .
    links:
      - postgresql:postgresql.local
    environment:
      - SERVICE_NAME=here-goes-service-name
      - NODE_ENV=production
      - POSTGRESQL_HOST=postgresql.local
      - POSTGRESQL_PORT=5432
      - POSTGRESQL_USER=admin
      - POSTGRESQL_PASSWORD=12345
      - POSTGRESQL_NAME=dbname
    command: >
      /bin/sh -c "
        set -e
        env
        dockerize -wait tcp://$$POSTGRESQL_HOST:$$POSTGRESQL_PORT
        npm run --silent migrate:schema
        npm run --silent migrate:seeds
        echo Starting application
        npm --silent start
      "
