version: '2'
services:
  postgresql:
    image: mdillon/postgis:9.4-alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=dbname
    ports:
      - 15432:5432

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 8081:15672

  test-unit:
    image: node:8
    volumes:
      - .:/opt/app
    environment:
      - NODE_ENV=production
      - POSTGRESQL_HOST=postgresql.local
      - POSTGRESQL_PORT=5432
      - POSTGRESQL_USER=admin
      - POSTGRESQL_PASSWORD=12345
      - POSTGRESQL_NAME=dbname
      - AMQP_HOST=amqp.local
      - AMQP_PORT=5672
      - AMQP_USER=guest
      - AMQP_PASSWORD=guest
    working_dir: /opt/app
    command: "npm run test:unit"

  test-functional:
    image: node:8
    depends_on:
      - postgresql
      - rabbitmq
    links:
      - postgresql:postgresql.local
      - rabbitmq:amqp.local
    build: .
    environment:
      - NODE_ENV=production
      - POSTGRESQL_HOST=postgresql.local
      - POSTGRESQL_PORT=5432
      - POSTGRESQL_USER=admin
      - POSTGRESQL_PASSWORD=12345
      - POSTGRESQL_NAME=dbname
      - AMQP_HOST=amqp.local
      - AMQP_PORT=5672
      - AMQP_USER=guest
      - AMQP_PASSWORD=guest
    working_dir: /opt/app
    command: >
      /bin/sh -c "
        #set -e
        dockerize -wait tcp://$$POSTGRESQL_HOST:$$POSTGRESQL_PORT -wait tcp://$$AMQP_HOST:$$AMQP_PORT
        npm run --silent migrate:schema
        npm run --silent migrate:seeds
        npm run --silent migrate:testSeeds
        echo Starting application
        npm --silent start &
        sleep 5
        node -v
        npm run test:functional
        ps aux
      "

  run:
    depends_on:
      - postgresql
      - rabbitmq
    build: .
    links:
      - postgresql:postgresql.local
      - rabbitmq:amqp.local
    environment:
      - NODE_ENV=production
      - POSTGRESQL_HOST=postgresql.local
      - POSTGRESQL_PORT=5432
      - POSTGRESQL_USER=admin
      - POSTGRESQL_PASSWORD=12345
      - POSTGRESQL_NAME=dbname
      - AMQP_HOST=amqp.local
      - AMQP_PORT=5672
      - AMQP_USER=guest
      - AMQP_PASSWORD=guest
    command: >
      /bin/sh -c "
        set -e
        dockerize -wait tcp://$$POSTGRESQL_HOST:$$POSTGRESQL_PORT -wait tcp://$$AMQP_HOST:$$AMQP_PORT
        npm run --silent migrate:schema
        npm run --silent migrate:seeds
        echo Starting application
        npm --silent start
      "
